name: 'Push Windmill'
on:
  push:
    branches:
      - 'main'

env:
  WMILL_URL: https://app.windmill.dev/
  WMILL_WORKSPACE: push-demo

concurrency:
  group: 'wmill-push'

jobs:
  sync:
    environment:
      name: windmill 
      url: ${{ env.WMILL_URL }}?workspace=${{ env.WMILL_WORKSPACE }}
    runs-on: "ubuntu-latest"
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: vx.x.x

      # TODO: Replace with https://deno.land/x/wmill@v??/main.ts or a custom action
      - name: Setup wmill
        run: deno run --unstable -A https://raw.githubusercontent.com/HurricanKai/windmill/sync2/cli/main.ts workspace add __automation ${{ env.WMILL_WORKSPACE }} ${{ env.WMILL_URL }} --token ${{ secrets.WMILL_TOKEN }}

      - name: Push newly made changes
        run: deno run --unstable -A https://raw.githubusercontent.com/HurricanKai/windmill/sync2/cli/main.ts sync push --raw                                                                                                          